### Importing necessary libraries

In [181]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
from pathlib import Path

### Importing the raw data file

In [182]:
data_path = Path.cwd().parent.joinpath("data", "raw")
file_path = os.path.join(data_path, "olkaria_unit_1.xlsx")
file = pd.ExcelFile(file_path)

# Get the sheet names
sheet_names = file.sheet_names
print("Available sheets in the file:")
for i, name in enumerate(sheet_names, 1):
    print(f"{i}. {name}")

Available sheets in the file:
1.  SUMMARY DATA FOR UNIT 1 OLK II
2. LOAD STEAM PRES FLOW TEMP DATA
3.   scrubber inlet pre,turbine te
4. data for net power to kenya pow

In [183]:
# Load the most important sheets
df_sheet_main = pd.read_excel(file_path, sheet_name=sheet_names[1])
df_sheet_turbine = pd.read_excel(file_path, sheet_name=sheet_names[2])

In [184]:
# Sheet 1
df_sheet_main.head(10)

,Dates,Gen1 Unit Load (MW),Gen2 Unit Load (MW),Gen3 Unit Load (MW),Gen1 Vent Station Steam Pressure Bar,Gen2 Vent Station Steam Pressure Bar,Gen3 Vent Station Steam Pressure Bar,Gen1 Main steam flow (T/H),Gen2 Main steam flow (T/H),Gen3 Main steam flow (T/H),Gen1 Main Steam Temp °C(Scrubber inlet),Gen2 Main Steam Temp °C(Scrubber inlet),Gen3 Main Steam Temp °C(Scrubber inlet),Gen1 Bar (Scrubber inlet) Main steam pressure,Gen2 Bar (Scrubber inlet) Main steam pressure,Gen3 Bar (Scrubber inlet) Main steam pressure,Unnamed: 16
0,HOURS,2000/0800,2400/1200,0 400 /1600,2000/0800,2400/1200,0 400 /1600,2000/0800,2400/1200,0 400 /1600,2000/0800,2400/1200,0 400 /1600,2000/0800,2400/1200,0 400 /1600,NaN
1,2018-01-11 00:00:00,30.5,30.1,30.3,5.47,5.47,5.46,261.3,260.1,263.6,159.1,159.2,159.1,5,5,NaN,NaN
2,2018-02-11 00:00:00,30.4,25.3,25.5,5.51,5.5,5.49,264.3,220.4,217.2,159.1,159.3,159.5,5,5,5,NaN
3,2018-02-11 00:00:00,30.7,30.7,NaN,5.65,5.64,NaN,266.4,266.8,NaN,159.9,159.9,NaN,5.5,5.5,NaN,NaN
4,2018-03-11 00:00:00,25.7,25.7,25.7,5.66,5.69,5.69,237.3,239.2,259.2,150.4,150.3,150.3,5.6,5.6,5.6,NaN
5,2018-03-11 00:00:00,30.8,25,NaN,5.49,5.51,NaN,266.2,237.9,NaN,159.2,159.4,NaN,5.4,5.4,NaN,NaN
6,2018-04-11 00:00:00,25.7,25.6,25.6,5.67,5.67,5.67,241.3,241.3,241.3,160.2,160.2,160.2,5.6,5.6,5.6,NaN
7,2018-04-11 00:00:00,25.6,24.5,25.4,5.5,5.95,5.47,243.2,25,232,159.5,159.2,159.4,5.4,5.4,5.4,NaN
8,2018-05-11 00:00:00,30.8,30.9,30.3,5.47,5.46,5.47,260.7,259.4,251.9,158,158.5,158.9,5.3,5.3,5.3,NaN
9,2018-05-11 00:00:00,25.3,25.6,30.4,5.42,5.45,5.45,240,239,262,159,159,159,5.3,5.3,5.3,NaN

In [185]:
# Sheet 2
df_sheet_turbine.head(10)

,Date,Gen1 Main Steam Temp Tubine Inlet(°C) (LH),Gen2 Main Steam Temp Tubine Inlet(°C) (LH),Gen3 Main Steam Temp Tubine Inlet(°C) (LH),Gen1 Main Steam Temp Tubine Inlet(°C) (RH),Gen2 Main Steam Temp Tubine Inlet(°C) (RH),Gen3 Main Steam Temp Tubine Inlet(°C) (RH),Gen1 Main steam Conductivity μ MHO,Gen2 Main steam Conductivity μ MHO,Gen3 Main steam Conductivity μ MHO,...,Gen2 Turbine Chest Pressure (Bar g),Gen3 Turbine Chest Pressure (Bar g),Gen1 Turbine exhaust Steam pressure Bar a,Gen2 Turbine exhaust Steam pressure Bar a,Gen3 Turbine exhaust Steam pressure Bar a,Gen1 Turbine Exhaust Steam temp,Gen2 Turbine Exhaust Steam temp,Gen3 Turbine Exhaust Steam temp,Unnamed: 19,Unnamed: 20
0,HOURS,2000/0800,2400/1200,0 400 /1600,2000/0800,2400/1200,0 400 /1600,2000/0800,2400/1200,0 400 /1600,...,2400/1200,0 400 /1600,2000/0800,2400/1200,0 400 /1600,2000/0800,2400/1200,0 400 /1600,NaN,NaN
1,2018-01-11 00:00:00,154.6,154.8,154.6,158.5,158.7,158.5,4,3.4,3.2,...,5.16,5.202,0.122,0.119,0.121,50.1,49.3,49.8,NaN,NaN
2,2018-02-11 00:00:00,154.7,155.3,155.4,158.6,159.2,159.3,3,10.4,6.8,...,4.12,4.096,0.123,0.096,0.095,50.2,45.3,44.7,NaN,NaN
3,2018-02-11 00:00:00,155.4,155.4,NaN,159.3,159.3,NaN,4.4,4.4,NaN,...,5.329,NaN,0.125,0.125,NaN,50.1,50.7,NaN,NaN,NaN
4,2018-03-11 00:00:00,156.1,156.1,156.1,159.9,160,160,3.8,3.8,3.8,...,4.657,4.657,0.139,0.14,0.14,52.4,52.4,52.4,NaN,NaN
5,2018-03-11 00:00:00,154.8,155,NaN,158.7,158.8,NaN,8,8.2,NaN,...,4.611,NaN,0.126,0.139,NaN,50.4,52.1,NaN,NaN,NaN
6,2018-04-11 00:00:00,156,156,156,159,159,159,3.4,3.4,3.4,...,4.602,4.602,0.137,0.137,0.137,52.2,52.2,52.2,NaN,NaN
7,2018-04-11 00:00:00,155,159.6,155,158.8,158.6,155,4.4,6.2,7,...,4.55,4.461,0.143,0.139,0.131,52.9,52.7,51.6,NaN,NaN
8,2018-05-11 00:00:00,154.4,154.7,154.6,158.3,158,158.4,3,3,3.4,...,5.123,5.053,0.116,0.112,0.111,49.2,48.5,48,NaN,NaN
9,2018-05-11 00:00:00,154.5,154.5,154.2,158.3,158.3,158,3.6,11.6,3.4,...,4.675,5.101,0.14,0.145,0.115,52.4,53.8,49.4,NaN,NaN

In [186]:
# Drop the unnamed columns
df_sheet_main = df_sheet_main.drop(columns=["Unnamed: 16"])
df_sheet_turbine = df_sheet_turbine.drop(columns = ["Unnamed: 19", "Unnamed: 20"])

In [187]:
# Gen1 — takes column 0 (date) + columns 1, 4, 7, 10, 13
gen1_load_raw = df_sheet_main.iloc[:, [0, 1, 4, 7, 10, 13]].copy()
gen1_load_raw.columns = [
    'date',
    'load_MW',
    'vent_pressure_bar',
    'steam_flow_th',
    'scrubber_temp_C',
    'scrubber_pressure_bar'
]

# Gen2 — takes column 0 (date) + columns 2, 5, 8, 11, 14
gen2_load_raw = df_sheet_main.iloc[:, [0, 2, 5, 8, 11, 14]].copy()
gen2_load_raw.columns = [
    'date',
    'load_MW',
    'vent_pressure_bar',
    'steam_flow_th',
    'scrubber_temp_C',
    'scrubber_pressure_bar'
]

# Gen3 — takes column 0 (date) + columns 3, 6, 9, 12, 15
gen3_load_raw = df_sheet_main.iloc[:, [0, 3, 6, 9, 12, 15]].copy()
gen3_load_raw.columns = [
    'date',
    'load_MW',
    'vent_pressure_bar',
    'steam_flow_th',
    'scrubber_temp_C',
    'scrubber_pressure_bar'
]

print("Gen1 Load raw shape:", gen1_load_raw.shape)
display(gen1_load_raw.head(5))

print("Gen2 Load raw shape:", gen2_load_raw.shape)
display(gen2_load_raw.head(5))

print("Gen3 Load raw shape:", gen3_load_raw.shape)
display(gen3_load_raw.head(5))

Gen1 Load raw shape: (190, 6)

,date,load_MW,vent_pressure_bar,steam_flow_th,scrubber_temp_C,scrubber_pressure_bar
0,HOURS,2000/0800,2000/0800,2000/0800,2000/0800,2000/0800
1,2018-01-11 00:00:00,30.5,5.47,261.3,159.1,5
2,2018-02-11 00:00:00,30.4,5.51,264.3,159.1,5
3,2018-02-11 00:00:00,30.7,5.65,266.4,159.9,5.5
4,2018-03-11 00:00:00,25.7,5.66,237.3,150.4,5.6

Gen2 Load raw shape: (190, 6)

,date,load_MW,vent_pressure_bar,steam_flow_th,scrubber_temp_C,scrubber_pressure_bar
0,HOURS,2400/1200,2400/1200,2400/1200,2400/1200,2400/1200
1,2018-01-11 00:00:00,30.1,5.47,260.1,159.2,5
2,2018-02-11 00:00:00,25.3,5.5,220.4,159.3,5
3,2018-02-11 00:00:00,30.7,5.64,266.8,159.9,5.5
4,2018-03-11 00:00:00,25.7,5.69,239.2,150.3,5.6

Gen3 Load raw shape: (190, 6)

,date,load_MW,vent_pressure_bar,steam_flow_th,scrubber_temp_C,scrubber_pressure_bar
0,HOURS,0 400 /1600,0 400 /1600,0 400 /1600,0 400 /1600,0 400 /1600
1,2018-01-11 00:00:00,30.3,5.46,263.6,159.1,NaN
2,2018-02-11 00:00:00,25.5,5.49,217.2,159.5,5
3,2018-02-11 00:00:00,NaN,NaN,NaN,NaN,NaN
4,2018-03-11 00:00:00,25.7,5.69,259.2,150.3,5.6

In [188]:
# Gen1 — col 0 (date) + cols 1,4,7,10,13,16
gen1_turbine_raw = df_sheet_turbine.iloc[:, [0, 1, 4, 7, 10, 13, 16]].copy()
gen1_turbine_raw.columns = [
    'date',
    'lh_inlet_temp_C',
    'rh_inlet_temp_C',
    'conductivity_uMHO',
    'chest_pressure_barg',
    'exhaust_pressure_bara',
    'exhaust_temp_C'
]

# Gen2 — col 0 (date) + cols 2,5,8,11,14,17
gen2_turbine_raw = df_sheet_turbine.iloc[:, [0, 2, 5, 8, 11, 14, 17]].copy()
gen2_turbine_raw.columns = [
    'date',
    'lh_inlet_temp_C',
    'rh_inlet_temp_C',
    'conductivity_uMHO',
    'chest_pressure_barg',
    'exhaust_pressure_bara',
    'exhaust_temp_C'
]

# Gen3 — col 0 (date) + cols 3,6,9,12,15,18
gen3_turbine_raw = df_sheet_turbine.iloc[:, [0, 3, 6, 9, 12, 15, 18]].copy()
gen3_turbine_raw.columns = [
    'date',
    'lh_inlet_temp_C',
    'rh_inlet_temp_C',
    'conductivity_uMHO',
    'chest_pressure_barg',
    'exhaust_pressure_bara',
    'exhaust_temp_C'
]


print("Gen1 Turbine raw shape:", gen1_turbine_raw.shape)
display(gen1_turbine_raw.head(5))

print("Gen2 Turbine raw shape:", gen2_turbine_raw.shape)
display(gen2_turbine_raw.head(5))

print("Gen3 Turbine raw shape:", gen3_turbine_raw.shape)
display(gen3_turbine_raw.head(5))

Gen1 Turbine raw shape: (190, 7)

,date,lh_inlet_temp_C,rh_inlet_temp_C,conductivity_uMHO,chest_pressure_barg,exhaust_pressure_bara,exhaust_temp_C
0,HOURS,2000/0800,2000/0800,2000/0800,2000/0800,2000/0800,2000/0800
1,2018-01-11 00:00:00,154.6,158.5,4,5.211,0.122,50.1
2,2018-02-11 00:00:00,154.7,158.6,3,5.248,0.123,50.2
3,2018-02-11 00:00:00,155.4,159.3,4.4,5.329,0.125,50.1
4,2018-03-11 00:00:00,156.1,159.9,3.8,4.662,0.139,52.4

Gen2 Turbine raw shape: (190, 7)

,date,lh_inlet_temp_C,rh_inlet_temp_C,conductivity_uMHO,chest_pressure_barg,exhaust_pressure_bara,exhaust_temp_C
0,HOURS,2400/1200,2400/1200,2400/1200,2400/1200,2400/1200,2400/1200
1,2018-01-11 00:00:00,154.8,158.7,3.4,5.16,0.119,49.3
2,2018-02-11 00:00:00,155.3,159.2,10.4,4.12,0.096,45.3
3,2018-02-11 00:00:00,155.4,159.3,4.4,5.329,0.125,50.7
4,2018-03-11 00:00:00,156.1,160,3.8,4.657,0.14,52.4

Gen3 Turbine raw shape: (190, 7)

,date,lh_inlet_temp_C,rh_inlet_temp_C,conductivity_uMHO,chest_pressure_barg,exhaust_pressure_bara,exhaust_temp_C
0,HOURS,0 400 /1600,0 400 /1600,0 400 /1600,0 400 /1600,0 400 /1600,0 400 /1600
1,2018-01-11 00:00:00,154.6,158.5,3.2,5.202,0.121,49.8
2,2018-02-11 00:00:00,155.4,159.3,6.8,4.096,0.095,44.7
3,2018-02-11 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN
4,2018-03-11 00:00:00,156.1,160,3.8,4.657,0.14,52.4

In [189]:
# Drop the hours row
gen1_load_raw = gen1_load_raw.iloc[1:].reset_index(drop=True)
gen2_load_raw = gen2_load_raw.iloc[1:].reset_index(drop=True)
gen3_load_raw = gen3_load_raw.iloc[1:].reset_index(drop=True)

gen1_turbine_raw = gen1_turbine_raw.iloc[1:].reset_index(drop=True)
gen2_turbine_raw = gen2_turbine_raw.iloc[1:].reset_index(drop=True)
gen3_turbine_raw = gen3_turbine_raw.iloc[1:].reset_index(drop=True)

print("Gen1 Load raw shape:", gen1_load_raw.shape)
display(gen1_load_raw.head(5))

print("Gen2 Load raw shape:", gen2_load_raw.shape)
display(gen2_load_raw.head(5))

print("Gen3 Load raw shape:", gen3_load_raw.shape)
display(gen3_load_raw.head(5))


print("Gen1 Turbine raw shape:", gen1_turbine_raw.shape)
display(gen1_turbine_raw.head(5))

print("Gen2 Turbine raw shape:", gen2_turbine_raw.shape)
display(gen2_turbine_raw.head(5))

print("Gen3 Turbine raw shape:", gen3_turbine_raw.shape)
display(gen3_turbine_raw.head(5))

Gen1 Load raw shape: (189, 6)

,date,load_MW,vent_pressure_bar,steam_flow_th,scrubber_temp_C,scrubber_pressure_bar
0,2018-01-11 00:00:00,30.5,5.47,261.3,159.1,5
1,2018-02-11 00:00:00,30.4,5.51,264.3,159.1,5
2,2018-02-11 00:00:00,30.7,5.65,266.4,159.9,5.5
3,2018-03-11 00:00:00,25.7,5.66,237.3,150.4,5.6
4,2018-03-11 00:00:00,30.8,5.49,266.2,159.2,5.4

Gen2 Load raw shape: (189, 6)

,date,load_MW,vent_pressure_bar,steam_flow_th,scrubber_temp_C,scrubber_pressure_bar
0,2018-01-11 00:00:00,30.1,5.47,260.1,159.2,5
1,2018-02-11 00:00:00,25.3,5.5,220.4,159.3,5
2,2018-02-11 00:00:00,30.7,5.64,266.8,159.9,5.5
3,2018-03-11 00:00:00,25.7,5.69,239.2,150.3,5.6
4,2018-03-11 00:00:00,25,5.51,237.9,159.4,5.4

Gen3 Load raw shape: (189, 6)

,date,load_MW,vent_pressure_bar,steam_flow_th,scrubber_temp_C,scrubber_pressure_bar
0,2018-01-11 00:00:00,30.3,5.46,263.6,159.1,NaN
1,2018-02-11 00:00:00,25.5,5.49,217.2,159.5,5
2,2018-02-11 00:00:00,NaN,NaN,NaN,NaN,NaN
3,2018-03-11 00:00:00,25.7,5.69,259.2,150.3,5.6
4,2018-03-11 00:00:00,NaN,NaN,NaN,NaN,NaN

Gen1 Turbine raw shape: (189, 7)

,date,lh_inlet_temp_C,rh_inlet_temp_C,conductivity_uMHO,chest_pressure_barg,exhaust_pressure_bara,exhaust_temp_C
0,2018-01-11 00:00:00,154.6,158.5,4,5.211,0.122,50.1
1,2018-02-11 00:00:00,154.7,158.6,3,5.248,0.123,50.2
2,2018-02-11 00:00:00,155.4,159.3,4.4,5.329,0.125,50.1
3,2018-03-11 00:00:00,156.1,159.9,3.8,4.662,0.139,52.4
4,2018-03-11 00:00:00,154.8,158.7,8,5.221,0.126,50.4

Gen2 Turbine raw shape: (189, 7)

,date,lh_inlet_temp_C,rh_inlet_temp_C,conductivity_uMHO,chest_pressure_barg,exhaust_pressure_bara,exhaust_temp_C
0,2018-01-11 00:00:00,154.8,158.7,3.4,5.16,0.119,49.3
1,2018-02-11 00:00:00,155.3,159.2,10.4,4.12,0.096,45.3
2,2018-02-11 00:00:00,155.4,159.3,4.4,5.329,0.125,50.7
3,2018-03-11 00:00:00,156.1,160,3.8,4.657,0.14,52.4
4,2018-03-11 00:00:00,155,158.8,8.2,4.611,0.139,52.1

Gen3 Turbine raw shape: (189, 7)

,date,lh_inlet_temp_C,rh_inlet_temp_C,conductivity_uMHO,chest_pressure_barg,exhaust_pressure_bara,exhaust_temp_C
0,2018-01-11 00:00:00,154.6,158.5,3.2,5.202,0.121,49.8
1,2018-02-11 00:00:00,155.4,159.3,6.8,4.096,0.095,44.7
2,2018-02-11 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN
3,2018-03-11 00:00:00,156.1,160,3.8,4.657,0.14,52.4
4,2018-03-11 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN

In [190]:
# Gen1 — merge load + turbine on date
gen1_raw = pd.merge(gen1_load_raw, gen1_turbine_raw, on='date', how='outer')

# Gen2
gen2_raw = pd.merge(gen2_load_raw, gen2_turbine_raw, on='date', how='outer')

# Gen3
gen3_raw = pd.merge(gen3_load_raw, gen3_turbine_raw, on='date', how='outer')

print("Gen1 raw shape:", gen1_raw.shape)
display(gen1_raw.head(5))
print()
print("Gen2 raw shape:", gen2_raw.shape)
display(gen2_raw.head(5))
print()
print("Gen3 raw shape:", gen3_raw.shape)
display(gen3_raw.head(5))

Gen1 raw shape: (371, 12)

,date,load_MW,vent_pressure_bar,steam_flow_th,scrubber_temp_C,scrubber_pressure_bar,lh_inlet_temp_C,rh_inlet_temp_C,conductivity_uMHO,chest_pressure_barg,exhaust_pressure_bara,exhaust_temp_C
0,2018-01-11 00:00:00,30.5,5.47,261.3,159.1,5,154.6,158.5,4,5.211,0.122,50.1
1,2018-01-12 00:00:00,28.1,5.4,244,158.1,5.3,154,158,3.4,5.165,0.111,48.1
2,2018-01-12 00:00:00,28.1,5.4,244,158.1,5.3,154,158.2,3.2,5.13,0.111,48
3,2018-01-12 00:00:00,28.5,5.39,244,158.6,5.3,154,158,3.4,5.165,0.111,48.1
4,2018-01-12 00:00:00,28.5,5.39,244,158.6,5.3,154,158.2,3.2,5.13,0.111,48

Gen2 raw shape: (371, 12)

,date,load_MW,vent_pressure_bar,steam_flow_th,scrubber_temp_C,scrubber_pressure_bar,lh_inlet_temp_C,rh_inlet_temp_C,conductivity_uMHO,chest_pressure_barg,exhaust_pressure_bara,exhaust_temp_C
0,2018-01-11 00:00:00,30.1,5.47,260.1,159.2,5,154.8,158.7,3.4,5.16,0.119,49.3
1,2018-01-12 00:00:00,28.4,5.4,244,158.5,5.3,154,158,2.8,5.154,0.107,47.2
2,2018-01-12 00:00:00,28.4,5.4,244,158.5,5.3,154.1,158.1,3.2,5.155,0.114,48.8
3,2018-01-12 00:00:00,28,5.39,245,158.7,5.3,154,158,2.8,5.154,0.107,47.2
4,2018-01-12 00:00:00,28,5.39,245,158.7,5.3,154.1,158.1,3.2,5.155,0.114,48.8

Gen3 raw shape: (371, 12)

,date,load_MW,vent_pressure_bar,steam_flow_th,scrubber_temp_C,scrubber_pressure_bar,lh_inlet_temp_C,rh_inlet_temp_C,conductivity_uMHO,chest_pressure_barg,exhaust_pressure_bara,exhaust_temp_C
0,2018-01-11 00:00:00,30.3,5.46,263.6,159.1,NaN,154.6,158.5,3.2,5.202,0.121,49.8
1,2018-01-12 00:00:00,28.3,5.4,246,158.3,5.3,154.1,158.1,2.8,5.155,0.112,48.1
2,2018-01-12 00:00:00,28.3,5.4,246,158.3,5.3,153.9,157.9,6.6,5.141,0.111,48.4
3,2018-01-12 00:00:00,28.7,5.41,245.2,158.6,5.3,154.1,158.1,2.8,5.155,0.112,48.1
4,2018-01-12 00:00:00,28.7,5.41,245.2,158.6,5.3,153.9,157.9,6.6,5.141,0.111,48.4

In [191]:
# Get the data types
print("Generator 1 Data Types: ")
print(gen1_raw.dtypes)
print("Generator 2 Data Types: ")
print(gen2_raw.dtypes)
print("Generator 3 Data Types: ")
print(gen3_raw.dtypes)

Generator 1 Data Types:
date                     object
load_MW                  object
vent_pressure_bar        object
steam_flow_th            object
scrubber_temp_C          object
scrubber_pressure_bar    object
lh_inlet_temp_C          object
rh_inlet_temp_C          object
conductivity_uMHO        object
chest_pressure_barg      object
exhaust_pressure_bara    object
exhaust_temp_C           object
dtype: object
Generator 2 Data Types:
date                     object
load_MW                  object
vent_pressure_bar        object
steam_flow_th            object
scrubber_temp_C          object
scrubber_pressure_bar    object
lh_inlet_temp_C          object
rh_inlet_temp_C          object
conductivity_uMHO        object
chest_pressure_barg      object
exhaust_pressure_bara    object
exhaust_temp_C           object
dtype: object
Generator 3 Data Types:
date                     object
load_MW                  object
vent_pressure_bar        object
steam_flow_th            object
scrubber_temp_C          object
scrubber_pressure_bar    object
lh_inlet_temp_C          object
rh_inlet_temp_C          object
conductivity_uMHO        object
chest_pressure_barg      object
exhaust_pressure_bara    object
exhaust_temp_C           object
dtype: object

In [192]:
# Check for null values
# Get the data types
print("Generator Null Values: ")
print(gen1_raw.isnull().sum())
print("Generator 2 Null Values: ")
print(gen2_raw.dtypes.isnull().sum())
print("Generator 3 Null Values: ")
print(gen3_raw.dtypes.isnull().sum())

Generator Null Values:
date                     12
load_MW                  29
vent_pressure_bar        29
steam_flow_th            29
scrubber_temp_C          29
scrubber_pressure_bar    31
lh_inlet_temp_C          26
rh_inlet_temp_C          26
conductivity_uMHO        28
chest_pressure_barg      26
exhaust_pressure_bara    26
exhaust_temp_C           26
dtype: int64
Generator 2 Null Values:
0
Generator 3 Null Values:
0